dimension:
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/postgres
    username: hopeng
    password:

another:
  datasource:
    jdbcUrl: jdbc:h2:mem:mydb
    username: sa
    password:

props.test:
  name: james
  description: lala
  note: hahaha llahe

spring:
  jpa:
    properties.hibernate.jdbc.lob.non_contextual_creation: true
    show-sql: true
