dimension:
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/postgres
    username: hopeng
    password:

another:
  datasource:
    jdbcUrl: jdbc:h2:mem:mydb
    username: sa
    password:

props.test:
  name: james
  description: lala
  note: hahaha llahe

spring:
  jpa:
    show-sql: true
    properties.hibernate.jdbc.lob.non_contextual_creation: true
    properties.hibernate.physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
